### ISSUE TITLE
штрихкод получаем из драйвера с неэкранированными спецсимволами

### ISSUE THREAD

**Issue by phsin** [innovait-rus/AtolSmartLiteUtils#2]
получаем из драйвера {"type": "Data Matrix", "data": "010464012186995521q"6/AOIlBD,pg 1720122893dGVz"} 
при разборе JSON - ошибка 
штрихкод насколько понимаю нужно конвертировать, спецсимволы экранировать, например " в `\"`

**Comment by innovait-rus** [comment]
Можно поправить в двух местах 
1. std::wstring ws_data = ToWStringJni(j_data); Тут добавить экранирование. 
2. Формировать JSON еще по пути вызова процедуры. 

Этот проект был создан как пример. Дальше каждый может собрать из него что хочет. Доработка в ближайшее время не планируется.
